version: "3.8"

services:
  postgresqldb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mfscreener
    ports:
      - "5432:5432"
    networks:
      - microservice-network
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8889:80"
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  db-data:
